-- Run this once in Supabase SQL Editor.
-- The application uses the tables below through the Supabase REST API.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  telegram_id text unique,
  username text,
  first_name text,
  stars integer not null default 0,
  is_premium integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.codes (
  id bigint generated by default as identity primary key,
  telegram_id text,
  code text unique,
  used integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.gifts (
  id bigint generated by default as identity primary key,
  name text not null,
  price integer not null default 0,
  image text,
  in_shop integer not null default 1,
  quantity integer,
  sold integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.user_gifts (
  id bigint generated by default as identity primary key,
  user_id bigint,
  gift_id bigint,
  obtained_at timestamptz not null default now()
);

create table if not exists public.gift_upgrades (
  id bigint generated by default as identity primary key,
  gift_id bigint not null,
  name text not null,
  counter integer not null default 0
);

create table if not exists public.upgrade_photos (
  id bigint generated by default as identity primary key,
  upgrade_id bigint not null,
  filename text not null
);

create table if not exists public.upgrade_models (
  id bigint generated by default as identity primary key,
  upgrade_id bigint not null,
  name text not null
);

create table if not exists public.user_gift_upgrades (
  id bigint generated by default as identity primary key,
  user_gift_id bigint not null,
  upgrade_id bigint not null,
  rarity text,
  rarity_color text,
  number integer,
  photo_filename text,
  model_name text,
  upgraded_at timestamptz not null default now()
);

create table if not exists public.marketplace (
  id bigint generated by default as identity primary key,
  user_gift_id bigint not null,
  seller_id bigint not null,
  price integer not null,
  status text not null default 'active',
  listed_at timestamptz not null default now()
);

create table if not exists public.auctions (
  id bigint generated by default as identity primary key,
  user_gift_id bigint not null,
  seller_id bigint not null,
  start_price integer not null,
  current_price integer not null,
  current_bidder_id bigint,
  end_time timestamptz not null,
  status text not null default 'active'
);

create table if not exists public.auction_bids (
  id bigint generated by default as identity primary key,
  auction_id bigint not null,
  bidder_id bigint not null,
  amount integer not null,
  bid_at timestamptz not null default now()
);

-- The server uses SUPABASE_KEY only; keep the tables accessible through the
-- REST API and do not expose the key in browser code.
grant select, insert, update, delete on all tables in schema public to anon, authenticated, service_role;
grant usage, select on all sequences in schema public to anon, authenticated, service_role;